myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('past/', views.past),
    path('contact/', views.contact),
    path('resource/', views.resource),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
    path('login/', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

posts/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

app_name = 'posts'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/enquiryform/', views.enquiryform,name = "enquiryform"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view,name = "register"),
    path('login/', views.login_view, name="login")

]

posts/models.py
from django.db import models

# Create your models here.
class Enquiry(models.Model):
    Name = models.CharField(max_length=75)
    Level = models.CharField(max_length=10)
    Course = models.CharField(max_length=30)
    Preferred_Timing = models.CharField(max_length=30)
    Contact = models.CharField(max_length=30, default='SOME STRING')

    
    def __str__(self):
        return self.title
    


users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm
from .models import Enquiry

class Enquiry(forms.ModelForm):
    class Meta:
        model = Enquiry
        fields = ('Name', 'Level', 'Course', 'Preferred_Timing', 'Contact',)


    def clean_level(self):
        data = self.cleaned_data.get('Name')
    
    def clean_Level(self):
        data = self.cleaned_data.get('Level')
    
    def clean_Course(self):
        data = self.cleaned_data.get('Course')
    
    def clean_Preferred_Timing(self):
        data = self.cleaned_data.get('Preferred_Timing')

    def clean_Contact(self):
        data = self.cleaned_data.get('Contact')


myproject/views.py
from django.shortcuts import render
#from django.http import HttpResponse

# Create your views here.
def homepage(request):
#      return HttpResponse("Hello World! I'm Home.")
      return render(request, 'home.html')

def about(request):
#    return HttpResponse("My About Page")
     return render(request, 'about.html')

def past(request):
     return render(request, 'past.html')

def contact(request):
     return render(request, 'contact.html')

def resource(request):
     return render(request, 'resource.html')

posts/views.py
from django.shortcuts import render
from .models import Enquiry
from . import forms
from .forms import Enquiry

def enquiryform(request, *args, **kwangs):
    form = Enquiry(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.save()
        form = Enquiry()
    return render(request, 'posts/enquiryform.html',{'form': form})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login

# Create your views here.
def register_view(request):
    if request.method == "POST":
      form = UserCreationForm(request.POST)
      if form.is_valid():
         login(request,form.save())
         return redirect("posts: list")
    else:
        form = UserCreationForm()
    return render(request,"users/register.html", {"form":form})

# Create your views here.
def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect("posts:list")     
    else:
        form = AuthenticationForm(request)
    return render(request,"users/login.html", {"form":form})

posts/templates/posts/enquiryform.html
{% extends 'layout.html' %}

{% block title %}
    Enquiry
{% endblock %}

{% block content %}
   <section>
        <h1> Enquiry </h1> </br>
         <form action=". " method=POST>
             {% csrf_token %}
             
             {{ form.as_p}}
             <input type="submit" value="Submit" class="btn btn-secondary">
         </form>
   </section>
{% endblock %}

templates/about.html
<!DOCTYPE html>
{% extends 'layout.html' %}

{% block title %}
     About
{% endblock %}

{% block content %}
   <h1> About </h1>
   <p> check out my <a href="/"> Home </a> page. </br>
   </br></br>
   
   </p>

   <h2> Result students could expect: </br>
   
   </h2>
   <p>    An improvement of 2 to 3 grades for 'O' level Pure Physics </br> 
          An improvement of 2 to 3 grades for 'A' level H1 students</br>
                                                            </br>   
   </p> 

{% endblock %}


 

templates/contact.html
{% extends 'layout.html' %}

{% block title %}
     Female Physics Tutor
{% endblock %}

{% block content %}
   <h1> Contact </h1>
   <p> check out my <a href="/about"> About </a> page. </br>
   </br>
   </p>
   
   <h2> Handphone:   </h2>
   <p>    97985804 </br> 
          
                    </br>   
   </p> 
   <h2> Email:   </h2>    
   <p>    femalephysicstutor@gmail.com </p>           

{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block title %}
     Female Physics Tutor
{% endblock %}

{% block content %}
   <h1> Female Physics Tutor </h1>
   <p> check out my <a href="/about"> About </a> page. </br>
   </br>
   </p>
   
   <h2> Education:   </h2>
   <p>    BSc.(Hon) (NUS) </br> 
          PGDE (NTU)</br>
                    </br>   
   </p> 
   <h2> Experience:   </h2>    
   <p>    RJC, PJC and secondary schools </p>           

{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App

        {% endblock%}
    </title>
    <link rel="stylesheet" href ="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body> 
    <nav>
           <a href = "/"> 
             <span role = "img" aria-label ="Home" >🎪 </span>
            </a> |
           <a href = "/about"> 
                <span role = "img" aria-label ="About" >😊 </span>
            </a> |
            <a href = "/past"> 
                <span role = "img" aria-label ="Past Students" > 🎃</span>
            </a> |
            <a href = "/contact"> 
            <span role = "img" aria-label ="Contact" >📠 </span> 
            </a> |

            <a href = "/resource"> 
                <span role = "img" aria-label ="Resource" >👜 </span> 
            </a> |
           <a href = "{% url 'posts:enquiryform' %}"> 
            <span role = "img" aria-label ="Enquiry" >📠 </span> 
           </a> |
           
    </nav>
    <main>
       {% block content %}

       {% endblock %}
    </main>
    
</body>
</html>

templates/past.html
{% extends 'layout.html' %}

{% block title %}
     Female Physics Tutor
{% endblock %}

{% block content %}
   <h1> Past students </h1>
   <p> check out my <a href="/about"> About </a> page. </br>
   </br>
   </p>
   
   <h2> Nanhua girl:   </h2>
   <p>    After attending my 1-to-1 tuition for 1.5 years, girl improved from C5 to A2 for 'O'level Pure Physics. </br> 
          
                    </br>   
   </p> 
   <h2> CHIJ girl:   </h2>    
   <p>    After attending my 1-to-1 tuition for 1.5 years, girl improved from C5 to A2 for 'O' level Pure Physics. </p>           

{% endblock %}

templates/resource.html

{% extends 'layout.html' %}

{% block title %}
     Resource
{% endblock %}

{% block content %}
   <h1> Resource </h1>
   <p> check out my <a href="/about"> About </a> page. </br>
   </br>
   </p>
   
   <h2> Physical Quantity, Units and Measurement: </br>  
   </br> 
   
    <iframe width="560" height="315" src="https://www.youtube.com/embed/s7uB48J3Z8s?si=ScvVVHWQmxpuUtyW" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </h2>
{% endblock %}

users/templates/users/login.html
<!DOCTYPE html>
{% extends 'layout.html' %}

{% block title %}
   User Login
{% endblock %}

{% block content %}
   <h1> User Login </h1>
   <form class = "form-with-validation"
       action = "/users/login/" method = 'post'>
       {% csrf_token %}{{ form }}
       <button class ="form-submit"> Submit<button>
       </form>
            
{% endblock %}



    

users/templates/users/register.html
<!DOCTYPE html>
{% extends 'layout.html' %}

{% block title %}
   Register a New User
{% endblock %}

{% block content %}
   <h1> Register a New User </h1>
   <form class = "form-with-validation"
       action = "/users/register/" method = 'post'>
       {% csrf_token %}{{ form }}
       <button class ="form-submit"> Submit<button>
       </form>
            
{% endblock %}



    